all:
	@echo Choose one of the targets:
	@echo "  run  "

run:
	./run_xrun.sh


clean: 
	rm -f *.log
	rm -f *.history
	rm -f *.key
	rm -f *.do
	rm -f *.rpt
	rm -f *.vRefine
	rm -rf INCA_libs INCA_libs_gui waves.shm xcelium.d cov_work
